service: serverless-api

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /

plugins:
  - serverless-offline
